---
abstract: 'SOAP interface to Hopkins'
author:
  - 'Mike Eldridge <diz@cpan.org>'
build_requires:
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hopkins-Plugin-RPC
requires:
  Class::Accessor::Fast: 0.31
  Getopt::Attribute: 1.44
  Hopkins: 0.900
  POE::Component::Server::SOAP: 1.11
  String::Escape: 2002.001
version: 0.900
